# Save this as git-credentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
type: Opaque
data:
  GITSYNC_USERNAME: YWhtZWRtbGFvdWhpYQ==
  GITSYNC_PASSWORD: Z2l0aHViX3BhdF8xMUFRUDdWNUkwb0tQa2l4ekk3U1JJX3NaSHdxc3htNDdtME9tRXBFellJano3Q09lc2FIOFpTMU4yTjdlUERLajNYNEgzSFdLVGdUcUFQdkhG
  GIT_SYNC_USERNAME: YWhtZWRtbGFvdWhpYQ==
  GIT_SYNC_PASSWORD: Z2l0aHViX3BhdF8xMUFRUDdWNUkwb0tQa2l4ekk3U1JJX3NaSHdxc3htNDdtME9tRXBFellJano3Q09lc2FIOFpTMU4yTjdlUERLajNYNEgzSFdLVGdUcUFQdkhG
